### ISSUE TITLE
Error when trying to seed

### ISSUE THREAD

**Issue by trobotham** [publiusfederalist/publius#1]
Hello! I am getting the following error when attempting to seed:

```
/root/publius/node_modules/webtorrent/index.js:106
      if (globalThis.WRTC && !this.tracker.wrtc) this.tracker.wrtc = globalThis.WRTC
      ^

ReferenceError: globalThis is not defined
    at new WebTorrent (/root/publius/node_modules/webtorrent/index.js:106:7)
    at Object.<anonymous> (/root/publius/seed:4:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

I installed the mentioned node modules in README, what am I missing?

**Comment by trobotham** [comment]
disregard this, my own fault for using a old node version, updated to node 17, it worked
